#!/bin/bash
# Based on autogenerated script from myrtle

export gemmDir="/repo/sw/kernels/blas/gemm_boundary"
export experimentDir=$(pwd)
export beta=0;
export spm_opt=1;
export TIMEOUT=0;

cd ..

bash myrtle-experiments/many_gemms.sh ./testrun/example.csv compile no no no > ./testrun/compile-example.txt;
bash myrtle-experiments/many_gemms.sh ./testrun/example.csv check run no no > ./testrun/run-example.txt;
python myrtle-experiments/combineTilingSchemeDataIntoSingleCSV.py ./testrun/example.csv $experimentDir;

cd $experimentDir